### PR TITLE
Add engineer vent option

### PR DESCRIPTION
**Pull request by AlexisL61**
Added option to choose if an engineer can vent in-game or not
By default, it is turn on.

### CODE REVIEW

**Comment by itsoskurr** [comment]
> Added option to choose if an engineer can vent in-game or not
> By default, it is turn on.

I don't think that's a good idea

**Comment by AlexisL61** [comment]
By playing with friends, we found that some of them use vent to show that they are not impostors.
That's why I think that's a good idea, and that's only an option.

**Comment by pedroumbelino** [comment]
Do other players watch you Vent? Cause to me the Engineer itself can see the Vent Animation but others can't. The player remains still on top of the Vent until the Engineers leaves the vent AND changes position

**Comment by NotHunter101** [comment]
Regarding the issue above, some of you probably don't have the mod, or you have conflicting versions. Regarding this PR, I will merge it after I test it and make sure everything works.

**Comment by pedroumbelino** [comment]
> Regarding the issue above, some of you probably don't have the mod, or you have conflicting versions. Regarding this PR, I will merge it after I test it and make sure everything works.

You're right. It works on NA servers. I was using the Imposter Server

**Comment by AlexisL61** [comment]
It seems that I push a test for a new role in the main branch. I will reset the commit so there will be only the engineer vent update

**Comment by NotHunter101** [comment]
I've thought about this a lot, and until I can better organize the already extensive list of game options, I can't add anything else that will make the mod even more complicated and daunting for newcomers.

**Pull request closed without merging**
