### PR TITLE
Feature/3.5s/essentials cooldown button

### PR DESCRIPTION
**Pull request by Popeye4242**

### CODE REVIEW

**Comment by Popeye4242** [comment]
- [ ] wait for Essentials dev.5

**Comment by DorCoMaNdO** [comment]
You should rebase this against the main branch since some of the commits belong to other PRs you made, some of which were merged.

**Comment by Popeye4242** [comment]
No, I cannot do that because this builds on #93 And I really don't want to resolve merge conflicts on a repo that has no otherwise activity.

**Comment by DorCoMaNdO** [comment]
0.2.0-dev.5 is now available.

**Comment by DorCoMaNdO** [comment]
I'll mention that you should probably make a derived class to change CanUpdateCooldown if you want it to match kill button behaviour, see dev.5 commit.

**Comment by Popeye4242** [comment]
Currently the button should behave like it did in v1.3.1 where it would count down further even if you open doors, right?

**Comment by DorCoMaNdO** [comment]
The original CooldownButton class did not check for PlayerControl.CanMove like the kill button, so the countdown was always ticking down, Essentials did implement this, but since I don't find the use of certain menus blocking the cooldown to be logical, I always planned to change it, the default behaviour now is that the cooldown only ticks during gameplay (when introcutscene, meetinghud and exilecontroller don't exist)

**Comment by Popeye4242** [comment]
I'll make an issue for this and address this later. I am too lazy right now to change this here.

**Comment by Popeye4242** [comment]
Closed in favour of #104

**Pull request closed without merging**
